#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Evangelos A. Dimopoulos, Evan K. Irving-Pease"
__copyright__ = "Copyright 2020, University of Oxford"
__email__ = "antonisdim41@gmail.com"
__license__ = "MIT"


include: "rules/download_paper_db.smk"

include: "rules/gargammel_sims.smk"


rule all:
    input:
        "paper_db/db_taxa_accessions.tsv",
        "all_garg_inputs_prepared.done",
        "raw_samples/effect_5652sp_120bp_0d.fastq.gz"
